djangoPhotoHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photography.urls')),
    path('users/', include('users.urls')),
    path('equipment/', include('equipment.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('profile/', views.profile_detail, name='profile'),
]

equipment/models.py
import uuid

from django.db import models

from users.models import Profile


# Create your models here.


class Camera(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name


class Lens(models.Model):
    camera = models.ForeignKey(Camera, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

photography/models.py
import uuid

from django.db import models
from users.models import Profile

# Create your models here.


class Photography(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=400)
    image = models.ImageField()
    up_votes = models.IntegerField(default=0, null=True, blank=True)
    down_votes = models.IntegerField(default=0, null=True, blank=True)
    category = models.ManyToManyField('Category')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Comment(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    photography = models.ForeignKey(Photography, on_delete=models.CASCADE)
    body = models.TextField(max_length=400, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.body


class RatingLikeDislike(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    photography = models.ForeignKey(Photography, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=500, blank=True, null=True)
    profile_image = models.ImageField(upload_to='profile/', blank=True, null=True, default='profile/user-default.png')
    social_instagram = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_facebook = models.CharField(max_length=200, blank=True, null=True)
    social_forum = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput, PasswordInput

from users.models import Profile


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

        widgets = {
            'username': TextInput(attrs={
                'class': 'form-control',
                'id': 'username_login'
            }),
            'password': PasswordInput(attrs={
                'class': 'form-control',
                'id': 'password_login'
            })
        }


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': 'Please enter your username',
                'id': 'username_register'
            }
        )
        self.fields['email'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': 'Please enter your username',
                'id': 'email_register'
            }
        )
        self.fields['password1'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': 'Please enter your password',
                'id': 'pass1_register'
            }
        )
        self.fields['password2'].widget.attrs.update(
            {
                'class': 'form-control',
                'placeholder': 'Please enter your confirmation password',
                'id': 'pass2_register'
            }
        )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description', 'profile_image', 'social_instagram', 'social_youtube', 'social_forum',
                  'social_facebook', 'location']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['description'].widget.attrs.update(
            {
                'class': 'form-control',
                'id': 'profile_description',
                'rows': '3'
            }
        )
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    'class': 'form-control',
                    'id': f'{field}'
                }
            )

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, TemplateView, CreateView, UpdateView

from equipment.forms import LensForm
from photography.forms import CreatePostPhoto
from users.forms import ProfileForm
from users.models import Profile


def profile_detail(request):
    profile = request.user.profile
    lens_form = LensForm()
    profile_form = ProfileForm(instance=profile)
    profile = Profile.objects.get(id=request.user.profile.id)

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('profile')
    return render(request, 'users/profile.html',
                  {'profile': profile,
                   'form': lens_form,
                   'profile_form': profile_form,
                   'form_create_photo': CreatePostPhoto()})

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Profile
{% endblock %}
{% block content %}
  <div class="container-lg mt-4 ms-auto">
    <div class="row">
      <div class="col-lg-4 position-relative">
        <button id="edit_profile_button" style="display: none" data-bs-toggle="modal" data-bs-target="#edit_profile"
                class="edit-page position-absolute border-0 top-0 end-0 badge rounded-pill bg-secondary">
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit Profile
        </button>
        <div class="profile-img-card">
          <div class="col-md-8 offset-md-2 text-center my-3 position relative">
            <img class="profile-img" src="{{ profile.profile_image.url }}"/>
            <h2 class="mt-2">@{{ profile.user }}</h2>
            <p style="color: rgb(80, 79, 79);">Located in {{ profile.location }}</p>
            <div class="container-fluid">
              {% if profile.social_facebook %}
                <a href="{{ profile.social_facebook }}" target="_blank" class="fa-icon"><i
                    class="fa fa-facebook-square fa-4" aria-hidden="true"></i></a>
              {% endif %}
              {% if profile.social_instagram %}
                <a href="{{ profile.social_instagram }}" target="_blank" class="fa-icon"><i
                    class="fa fa-instagram fa-3" aria-hidden="true"></i></a>
              {% endif %}
              {% if profile.social_youtube %}
                <a href="{{ profile.social_youtube }}" target="_blank" class="fa-icon"><i
                    class="fa fa-youtube-play" aria-hidden="true"></i></a>
              {% endif %}
            </div>
          </div>
          <div class="container-fluid">
            <p class="account-desc px-3 py-1">{{ profile.description }}
          </div>
        </div>
      </div>
      <div class="col-lg-8 position-relative">
        <h2 class="text-center"><b>ABOUT ME</b></h2>
        <button type="button" id="edit_page" onclick="show_edit()"
                class="position-absolute border-0 top-0 end-0 badge rounded-pill bg-primary">
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit Page
        </button>
        <div class="container-fluid">
          <p class="account-desc px-3 py-1">{{ profile.description }}</div>
        <h2 class="text-center"><b>Equipment</b></h2>
        <div class="px-4 pt-2 position-relative">
          <table id="camera_lens_table" class="table table-bordered x-3">
            <thead>
            <tr>
              <th>
                <div class="d-flex justify-content-between">
                  <div>Camera</div>
                  <div>
                    <button style="display: none" id="edit_camera_button" data-bs-toggle="modal"
                            data-bs-target="#edit_camera"
                            class="border-0 badge rounded-pill bg-secondary edit-page">
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add Camera
                    </button>
                  </div>
                </div>
              </th>
              <th>
                <div class="d-flex justify-content-between">
                  <div>Lens</div>
                  <div>
                    <button style="display: none" id="edit_lens_button" data-bs-toggle="modal"
                            data-bs-target="#edit_lens"
                            class="border-0 badge rounded-pill bg-secondary edit-page">
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Add Lens
                    </button>
                  </div>
                </div>
              </th>
            </tr>
            </thead>
            <tbody>
            {% for camera in profile.camera_set.all %}
              <tr>
                <td>{{ camera }}</td>
                <td>
                  <ul class="list-group list-group-flush">
                    {% for lens in camera.lens_set.all %}
                      <li class="list-group-item">{{ lens }}</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="row mt-2 mb-5">
      <h2 class="text-center"><b>POSTS</b></h2>
      <!-- Posts Cards -->
      {% for photography in profile.photography_set.all %}
        <div class="col-lg-4 col-sm-12 gy-2">
          <div class="card text-bg-dark account-card">
            <img src="{{ photography.image.url }}" class="card-img account-img-card" alt="...">
            <div class="card-img-overlay account-img-card-overlay">
              <h5 class="card-title">{{ photography.title }}</h5>
              <p class="card-text">{{ photography.description }}</p>
              <p class="card-text"><small>Last updated {{ photography.updated|timesince }}</small></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <!-- Modal for add camera -->
  <div class="modal fade" id="edit_camera" tabindex="-1" aria-labelledby="cameraLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post" action="{% url 'camera' %}">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Please add a camera</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <input type="text" class="form-control" name="camera" required>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- Modal for add lens -->
  <div class="modal fade" id="edit_lens" tabindex="-1" aria-labelledby="lensLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post" action="{% url 'lens' %}">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Please add a lens</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {{ form }}
            <input type="text" class="form-control mt-2" name="lens" placeholder="Please add lens" required>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!-- Modal for edit profile -->
  <div class="modal fade" id="edit_profile" tabindex="-1" aria-labelledby="profileLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Profile</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="POST" enctype="multipart/form-data">
          <div class="modal-body">
            {% csrf_token %}
            <div class="col-md-8 offset-md-2 text-center my-3">
              <div class="account-card">
                <label for="profile_image">
                  <img title="Click to edit" class="profile-img account-img-card" id="profile-img"
                       src="{{ profile.profile_image.url }}"/>
                </label>
              </div>
              <div style="display: none">
                {{ profile_form.profile_image }}
              </div>
              <h2 class="mt-2">@{{ profile.user }}</h2>
            </div>
            <div class="container-fluid mb-3">
              {% for field in profile_form %}
                {% if field.name != 'profile_image' %}
                  {{ field.label }}
                  {{ field }}
                {% endif %}
              {% endfor %}
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Update Profile
{% endblock %}
{% block content %}
  <div class="container-lg mt-2 ms-auto">
    <div class="row">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-6 offset-md-3 profile-img-card">
          <div class="col-md-8 offset-md-2 text-center my-3">
            <label for="profile_image">
              <img class="profile-img" id="profile-img" src="{{ profile.profile_image.url }}"/>
            </label>
            <div style="display: none">
              {{ profile_form.profile_image }}
            </div>
            <h2 class="mt-2">@{{ profile.user }}</h2>
          </div>
          <div class="container-fluid mb-3">
            {% for field in profile_form %}
              {% if field.name != 'profile_image' %}
                {{ field.label }}
                {{ field }}
              {% endif %}
            {% endfor %}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary mb-3">Update</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}